### ISSUE TITLE
Deletemailings.CleanMailing should use modified_date to select drafts to delete

### ISSUE THREAD

**Issue by semseysandor** [JMAConsulting/biz.jmaconsulting.deletemailings#2]
Currently `Deletemailings.CleanMailing` deletes draft mailings which was *created* before X days.
With this operation, the following can happen:
1. I (as a user) create a draft mailing
2. I forget about it for x-1 days
3. Then I remember to continue the draft with plans to finish and send it in a few days
4. The next day my draft is deleted by `Deletemailings.CleanMailing` and I'm suprised

So I propose to change `CleanMailing` to delete draft mailings which was last *modified* before x days.

I know it's a change of contract, but it would only delete certain drafts later (which was recently modified) and this operation is more natural: it deletes drafts which were not touched for a long time.

Note: I'm happy to open a PR if this is accepted

**Comment by JoeMurray** [comment]
Thanks @semseysandor ! @seamuslee001 pls qa

**Comment by seamuslee001** [comment]
Thanks @semseysandor for raising this issue, as this is no longer the canonical repository for this extension I have migrated this issue to https://lab.civicrm.org/extensions/deletemailings/-/issues/1 I'll comment further there
